### PR TITLE
Tests for the consoleLevel option

### PR DESCRIPTION
**Pull request by gmishkin**
Adds tests for the `consoleLevel` option I added in the last PR.

### CODE REVIEW

**Comment by justinjmoses** [comment]
friendly ping on this Geoff

**Comment by justinjmoses** [comment]
I typically don't publish forks - so the best bet is to just use `justinjmoses/hounds#master` no?

**Comment by gmishkin** [comment]
This is the format it was using before: https://github.com/gmishkin/hounds/commit/044c20ea4b7e53b93312ba9a7446678f3847f321#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L34

Is that `/tarball` path always available?

**Comment by justinjmoses** [comment]
It's definitely safer to tie to an explicit commit - so yeah you can continue that technique

**Comment by gmishkin** [comment]
RFAL

**Comment by justinjmoses** [comment]
Thanks Geoff!

**Pull request merged**
